name: CI workflow

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Install
        run: npm i
      - name: Build
        run: npm run build
      - name: Tests
        run: npm test
      - name: Tests e2e
        run: npm run test:e2e:ci
